services:
  backend:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/clashperk-backend:latest
    container_name: backend
    restart: always
    env_file:
      - .env
    environment:
      - PORT=8080
    ports:
      - '8080:8080'
    mem_limit: 1g
    networks:
      - default_net

networks:
  default_net:
    external: true
    name: default_net
