version: '3.6'

services:
  service-auth:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/service-auth:latest
    container_name: service-auth
    restart: always
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - .env
    mem_limit: 1gb

  service-capital:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/service-capital:latest
    container_name: service-capital
    restart: always
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - .env
    mem_limit: 1gb

  service-clans:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/service-clans:latest
    container_name: service-clans
    restart: always
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - .env
    mem_limit: 1gb

  service-wars:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/service-wars:latest
    container_name: service-wars
    restart: always
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - .env
    mem_limit: 1gb
