services:
  backend:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/clashperk-backend:latest
    container_name: backend
    restart: always
    env_file:
      - .env
    ports:
      - '8080:8080'
    mem_limit: 1g
    networks:
      - default_net

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clashperkdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    name: postgres_data
  redis_data:
    name: redis_data

networks:
  default_net:
    external: true
    name: default_net
