services:
  api:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/service-backend:latest
    container_name: api
    restart: always
    env_file:
      - .env
    ports:
      - '8081:8081'
    hostname: api
    mem_limit: 1g
