services:
  api:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/clashperk-api:latest
    container_name: service-api
    restart: always
    env_file:
      - .env
    environment:
      - PORT=8080
    ports:
      - '8080:8080'
    mem_limit: 1g
    networks:
      - default_net

  worker:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/clashperk-worker:latest
    container_name: service-worker
    restart: always
    env_file:
      - .env
    environment:
      - PORT=8090
      - RANKING_TRACKING=1
      - CLAN_TRACKING=1
      - CAPITAL_TRACKING=1
      - WAR_TRACKING=1
      - PLAYER_TRACKING=1
    ports:
      - '8090:8090'
    mem_limit: 2g
    networks:
      - default_net

networks:
  default_net:
    external: true
    name: default_net
